title: 소프트웨어 아키텍처 문서
description: 소프트웨어 아키텍처와 관련된 기술 문서 모음
remote_theme: just-the-docs/just-the-docs

url: https://garden92.github.io/kice-sw-jekyll
baseurl: /kice-sw-jekyll

# Just the Docs 테마 설정
# 검색 기능 강화
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# 네비게이션 설정
nav_external_links:
  - title: GitHub 저장소
    url: https://github.com/garden92/kice-sw-jekyll
    hide_icon: false

# 색상 테마는 커스텀 CSS로 처리
# color_scheme: dark

# 로고 및 파비콘 (선택사항)
logo: "/assets/images/logo.png"

# 플러그인
plugins:
  - jekyll-seo-tag
