source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1"
gem "webrick", "~> 1.8"

# Chirpy 테마를 위한 플러그인들
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-seo-tag"
  gem "jekyll-archives"
  gem "jekyll-redirect-from"
end
